version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    image: frontend:latest
    container_name: frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: > 
      /bin/bash -c "
      npm start
      "
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - network1
    volumes:
      - /app/node_modules
      - ./src:/app/src
      - ./public:/app/public

networks:
  network1:
    name: npx-api-network